### ISSUE TITLE
OMEMO guard against device stanza without ID

### ISSUE THREAD

**Issue by jubalh** [boothj5/profanity#1079]
@kaffeekanne got the following:

```
#0  0x00007f5c8ae594da in ____strtoull_l_internal () at /usr/lib/libc.so.6
#1  0x00005616709b4bb0 in _omemo_receive_devicelist (stanza=0x56167138b040, userdata=0x0) at src/xmpp/omemo.c:362
#2  0x000056167093eb29 in _message_handler (conn=0x561671203400, stanza=0x56167138b040, userdata=0x56167120d4f0) at src/xmpp/message.c:143
#3  0x00007f5c8b013719 in  () at /usr/lib/libstrophe.so.0
#4  0x00007f5c8b01027c in  () at /usr/lib/libstrophe.so.0
#5  0x00007f5c8b01c49f in  () at /usr/lib/libstrophe.so.0
#6  0x00007f5c89dc7927 in  () at /usr/lib/libexpat.so.1
#7  0x00007f5c89dc83cc in  () at /usr/lib/libexpat.so.1
#8  0x00007f5c89dca946 in XML_ParseBuffer () at /usr/lib/libexpat.so.1
#9  0x00007f5c8b013015 in xmpp_run_once () at /usr/lib/libstrophe.so.0
#10 0x0000561670937cef in connection_check_events () at src/xmpp/connection.c:99
#11 0x000056167093721f in session_process_events () at src/xmpp/session.c:271
#12 0x0000561670930b20 in prof_run (log_level=0x561670e2c990 "DEBUG", account_name=0x561670e2ca20 "tt") at src/profanity.c:127
#13 0x00005616709b51be in main (argc=1, argv=0x7ffeeaa83c58) at src/main.c:170
```

**Comment by kaffeekanne** [comment]
Well, not yet. Brace yourself, BT is comming...

**Comment by kaffeekanne** [comment]
does not look like omemo though, sorry

**Comment by jubalh** [comment]
Yeah lets create a new issue for this :)
