### ISSUE TITLE
Segfault in OpenSSL when reconneting

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#794]
Reported in chat room.  When a machine wakes up from sleep and profanity reconnects, the following segfault occurs.  `SSL_ctx_new()` appears to be returning NULL (see https://github.com/boothj5/libmesode/blob/master/src/tls_openssl.c#L251)

Try to recreate and fix the issue.

```
Thread 1 "profanity" received signal SIGSEGV, Segmentation fault.
0x00007ffff31b7de0 in SSL_CTX_set_client_cert_cb () from /usr/lib/libssl.so.1.0.0
(gdb) bt
#0  0x00007ffff31b7de0 in SSL_CTX_set_client_cert_cb () from /usr/lib/libssl.so.1.0.0
#1  0x00007ffff40121fd in ?? () from /usr/lib/libmesode.so.0
#2  0x00007ffff4006eb0 in ?? () from /usr/lib/libmesode.so.0
#3  0x00007ffff40076a9 in ?? () from /usr/lib/libmesode.so.0
#4  0x00007ffff400a86a in ?? () from /usr/lib/libmesode.so.0
#5  0x00007ffff4008084 in ?? () from /usr/lib/libmesode.so.0
#6  0x00007ffff401328e in ?? () from /usr/lib/libmesode.so.0
#7  0x00007fffeeb32e53 in ?? () from /usr/lib/libexpat.so.1
#8  0x00007fffeeb3377c in ?? () from /usr/lib/libexpat.so.1
#9  0x00007fffeeb37afb in XML_ParseBuffer () from /usr/lib/libexpat.so.1
#10 0x00007ffff400a0ad in xmpp_run_once () from /usr/lib/libmesode.so.0
#11 0x000000000041dfb7 in prof_run (log_level=<optimized out>, account_name=<optimized out>) at src/profanity.c:145
#12 0x000000000041aa19 in main (argc=1, argv=0x7fffffffe948) at src/main.c:148
(gdb) 
```

**Comment by asdil12** [comment]
More detailed info:

```
--> resume from standby

doesn't happen always, but here it happend:


Thread 1 "profanity" received signal SIGPIPE, Broken pipe.
0x00007ffff3bec09d in write () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff3bec09d in write () from /usr/lib/libpthread.so.0
#1  0x00007ffff2e24465 in sock_write () from /usr/lib/libcrypto.so.1.0.0
#2  0x00007ffff2e2229c in BIO_write () from /usr/lib/libcrypto.so.1.0.0
#3  0x00007ffff31915b2 in ssl3_write_pending () from /usr/lib/libssl.so.1.0.0
#4  0x00007ffff3193f6a in ssl3_dispatch_alert () from /usr/lib/libssl.so.1.0.0
#5  0x00007ffff318f252 in ssl3_shutdown () from /usr/lib/libssl.so.1.0.0
#6  0x00007ffff4011e0b in tls_stop (tls=0xfcfab0) at src/tls_openssl.c:325
#7  0x00007ffff4004cdf in conn_disconnect (conn=0xa58bc0) at src/conn.c:575
#8  0x00007ffff4006d05 in xmpp_run_once (ctx=0xdfc810, timeout=10) at src/event.c:300
#9  0x0000000000425413 in jabber_process_events (millis=10) at src/xmpp/connection.c:306
#10 0x000000000041e683 in prof_run (log_level=0x4a4830 "INFO", account_name=0x0) at src/profanity.c:145
#11 0x0000000000485716 in main (argc=1, argv=0x7fffffffe948) at src/main.c:148
(gdb) cont

...


--> /connect
21:40:40 - Using default account im.f3l.de.
21:40:40 - Connecting with account im.f3l.de as asdil12@im.f3l.de/profanity                                                                                    
                                                                                                                                                               Thread 1 "profanity" received signal SIGSEGV, Segmentation fault.
0x00007ffff31b2de0 in SSL_CTX_set_client_cert_cb () from /usr/lib/libssl.so.1.0.0
(gdb) bt
#0  0x00007ffff31b2de0 in SSL_CTX_set_client_cert_cb () from /usr/lib/libssl.so.1.0.0
#1  0x00007ffff4011b2e in tls_new (conn=0xe57640) at src/tls_openssl.c:251
#2  0x00007ffff40022d4 in _auth (conn=0xe57640) at src/auth.c:566
#3  0x00007ffff40018d3 in _handle_features (conn=0xe57640, stanza=0x1320f80, userdata=0x0) at src/auth.c:258
#4  0x00007ffff4007131 in handler_fire_stanza (conn=0xe57640, stanza=0x1320f80) at src/handler.c:101
#5  0x00007ffff4005b72 in _handle_stream_stanza (stanza=0x1320f80, userdata=0xe57640) at src/conn.c:1043
#6  0x00007ffff401315e in _end_element (userdata=0x13d60e0, name=0x17c8f10 "http://etherx.jabber.org/streams\037features") at src/parser_expat.c:157
#7  0x00007fffeeb2de53 in ?? () from /usr/lib/libexpat.so.1
#8  0x00007fffeeb2e77c in ?? () from /usr/lib/libexpat.so.1
#9  0x00007fffeeb3009e in ?? () from /usr/lib/libexpat.so.1
#10 0x00007fffeeb307f5 in ?? () from /usr/lib/libexpat.so.1
#11 0x00007fffeeb32afb in XML_ParseBuffer () from /usr/lib/libexpat.so.1
#12 0x00007ffff401341e in parser_feed (parser=0x13d60e0, chunk=0x7fffffffd660 "<?xml version='1.0'?><stream:stream xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' from='im.f3l.de' id='d59c4272-cfc5-4965-9577-6d4821977038' version='1.0' xmlns='jabber:client'><stream"..., len=358) at src/parser_expat.c:247
#13 0x00007ffff4006c3e in xmpp_run_once (ctx=0xdfc810, timeout=10) at src/event.c:287
#14 0x0000000000425413 in jabber_process_events (millis=10) at src/xmpp/connection.c:306
#15 0x000000000041e683 in prof_run (log_level=0x4a4830 "INFO", account_name=0x0) at src/profanity.c:145
#16 0x0000000000485716 in main (argc=1, argv=0x7fffffffe948) at src/main.c:148
```

**Comment by jubalh** [comment]
I remember that I have seen this somewhere.
I don't remember where :)
But I think it was fixed. So will close it until someone is bitten by it again :)
